---
title: "Manip des données"
author: "Andrew"
date: "26/09/2019"
output:
  html_document: 
    keep_md: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Manipulation des données c'est _fun_.

```{r loading_data}
library(tidyverse)
library(gapminder)
```

## regarde les données

```{r}
gapminder
```

## ggplot2

```{r}
ggplot(gapminder, aes(x = year, y = lifeExp)) + 
  geom_point()
```

Aussi possible avec des boxplots

```{r}
ggplot(gapminder, aes(x = year, y = lifeExp, group = year)) + 
  geom_boxplot() + 
  geom_point()
```

line plot

```{r}
ggplot(gapminder,
       aes(x = year,
           y = gdpPercap,
           group = country)) + 
  geom_line(colour = "darkgreen",
            size = 3,
            alpha = 0.1)
```

mapping to a group -- couleur par continent!

```{r}
ggplot(gapminder,
       aes(x = year,
           y = gdpPercap,
           group = country,
           colour = continent)) + 
  geom_line()
```

facets

```{r}
ggplot(gapminder,
       aes(x = year,
           y = gdpPercap,
           group = country,
           colour = continent)) + 
  geom_line() + 
  facet_wrap(~continent)
```

## manipuler avec dplyr

```{r intro_dplyr}
head(gapminder)

# choose columns
select(gapminder, country, year)

# observations after 2000
filter(gapminder, year > 2000)

# population in millions
mutate(gapminder, pop_millions = pop / 1e6)

## lowest populations
arrange(gapminder, pop)

arrange(gapminder, desc(lifeExp))
```

enchainer les operations!

`browseVignettes("magrittr")`

```{r}
set.seed(1234)
exp(mean(rnorm(20), trim = 2))

set.seed(1234)
rnorm(20) %>% mean(trim = 2) %>% exp

```

```{r dplyr_enchaine}
gapminder %>% 
  select(continent, country, year, pop) %>% 
  filter(continent == "Oceania") %>% 
  mutate(pop_mil = pop / 1e6)
```

## summarizing data

```{r}
gapminder %>% 
  ## average population by continent
  group_by(continent) %>% 
  summarize(median_gdp = median(gdpPercap),
            n_observations = n())
```

```{r}
gapminder %>% 
  # convert to millions
  mutate(pop_million = pop / 1e6) %>% 
  # calculate median per year per continent
  group_by(continent, year) %>% 
  summarise(med_pop = median(pop_million)) %>% 
  ggplot(aes(x = year, y = med_pop, colour = continent)) + 
  geom_line()
```

